=encoding utf8

=head1 Best Perl Modules

Perl 常用模块推荐。

=head2 模块安装

L<How to Install Perl Modules Using App::cpanminus (cpanm)|https://github.com/WisdomFusion/HOWTOs/blob/master/howto-install-perl-moudles-using-cpanminus.md>

=head2 推荐模块列表

=head3 Web Scraper

=over

=item * L<WWW::Mechanize>

=item * L<Scrappy>

=item * L<Web::Scraper>

=item * L<LWP>

=item * L<HTTP::Lite>

=item * L<HTTP::Tiny>

=item * L<WWW::Curl>

=back

HTML 处理：

=over

=item * L<HTML::Tree>

=item * L<HTML::TreeBuilder::XPath>

=item * L<HTML::TreeBuilder::Select>

=item * L<HTML::TreeBuilder::LibXML>

=back

=head3 Regular Expressions

=over

=item * L<Regexp::Common>

=item * L<Regexp::Optimizer>

=item * L<Regexp::Assemble>

=item * L<re>

=item * L<YAPE::Regex::Explain>

=back

=head3 Debug

=over

=item * L<Devel::Peek>

=item * L<Devel::Size>

=item * L<Devel::Trace>

=item * L<Carp::Always>

=item * L<Carp::Always::Color>

=item * L<Data::Dumper>

=item * L<Data::Dump>

=item * L<Data::Printer>

=item * L<Smart::Comments>

=item * L<Devel::REPL>

=item * L<Module::Info>

=item * L<PadWalker>

=back

=head3 Template

=over

=item * L<Template::Toolkit>

=item * L<HTML::Mason>

=item * L<Mason>

=item * L<Text::Xslate>

=item * L<HTML::Template>

=item * L<Text::Template>

=back

=head3 Web Frameworks

=over

=item * L<Mojolicious>

=item * L<Catalyst>

=item * L<Dancer>

=item * L<CGI::Application>

=item * L<Titanium>

=item * L<Jifty>

=item * L<Plack>

=back

=head3 Web Servers

=over

=item * L<Starman>

=item * L<PerlBal>

=item * L<Net::Server>

=item * L<HTTP::Daemon>

=item * L<HTTP::Server::Simple>

=item * L<POE::Component::Server::HTTP>

=item * L<POE::Component::Server::SimpleHTTP>

=item * L<POE::Loop::EV>

=item * L<POE::Loop::Event>

=item * L<POE::XS::Queue::Array>

=item * L<Mojo::Server::Hypnotoad>

=item * L<Twiggy>

=item * L<IO::Async>

=item * L<EV>

=item * L<AnyEvent>

=item * L<Coro>

=back

=head3 日期和时间

=over

=item * L<DateTime>

=item * L<Date::Tiny>

=item * L<Date::Parse>

=item * L<Time::ParseDate>

=item * L<Date::Formate>

=item * L<Time::HiRes>

=item * L<Date::Calc>

=back

=head3 databases

=over

=item * L<DBIx::Class>

=item * L<DBI>

=item * L<Class::DBI>

=item * L<Rose::DB::Object>

=item * L<DBIx::Simple>

=back

=head3 面向对象

=over

=item * L<Moose>

=item * L<MooseX>

=item * L<Mouse>

=item * L<Moo>

=item * L<Class::XSAccessor>

=item * L<Class::XSAccessor::Array>

=item * L<Class::Struct>

=item * L<Class::Accessor>

=item * L<Class::Std>

=item * L<Class::MethodMaker>

=item * L<App::Benchmark::Accessors>

=back

=head3 Email

=over

=item * L<Email::Sender>

=item * L<Email::Sender::Simple>

=item * L<Email::Stuffer>

=item * L<Mail::SendEasy>

=item * L<Mail::Mailer>

=item * L<Mail::Sendmail>

=back

=head3 IP

=over

=item * L<NetAddr::IP>

=item * L<Net::IP>

=item * L<Net::IP::XS>

=item * L<Net::IPv4Addr>

=item * L<Net::IPv6Addr>

=item * L<Net::IP::AddrRanges>

=item * L<Net::CIDR::Lite>

=item * L<Data::Validate::IP>

=item * L<IO::Socket::IP>

=back

=head3 Unicode

=over

=item * L<Unicode::Unihan>

=item * L<Unicode::Normalize>

=item * L<charnames>

=item * L<utf8>

=back

=head3 XML 处理

=over

=item * L<XML::LibXML>

=item * L<XML::Rules>

=item * L<XML::Simple>

=item * L<XML::Twig>

=back

=head3 Misc

=over

=item * L<App::Ack>

=item * L<Excel::Writer::XLSX>

=item * L<AnyEvent>

=item * L<POE>

=item * L<Coro>

=item * L<perl5i>

=item * L<Perl::Tidy>

=item * L<Modern::Perl>

=item * L<Exporter>

=item * L<Autodie>

=item * L<List::Util>

=item * L<List::Utils>

=item * L<List::MoreUtils>

=item * L<List::AllUtils>

=item * L<Scalar::Util>

=item * L<Hash::Util>

=item * L<Util::Any>

=item * L<Path::Class>

=back

=head2 Task::Kensho

L<Task::Kensho>
